config/routes.rb
Rails.application.routes.draw do
	mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	devise_for :users, class_name: "User",
	:controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions', :passwords => 'users/passwords' },
	path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
	root :to => "dashboard#index"
	resources :mail_templates do
		collection do
			delete 'destroy_multiple'
		end
	end
	get "send_mail_template/:id", to: 'mail_templates#send_mail_template', as: :send_mail_template
	patch "send_csv_mail_template/:id", to: 'mail_templates#send_csv_mail_template', as: :send_csv_mail_template
end

app/models/mail_template.rb
class MailTemplate < ApplicationRecord
	require 'csv'
	attr_accessor :mail_list, :csv
	validates_uniqueness_of :subject
	validates_presence_of :subject, :content
	include Bootsy::Container
	
	def readFile
		list = Array.new
		CSV.foreach(csv.path, headers: true) do |row|
			list.push(row.to_s.gsub("\n","").split.join)
		end
		list
	end
end

app/controllers/mail_templates_controller.rb
class MailTemplatesController < ApplicationController
  before_action :set_mail_template, only: [:show, :edit, :update, :destroy, :send_mail_template, :send_csv_mail_template]

  # GET /mail_templates
  # GET /mail_templates.json
  def index
    @mail_templates = MailTemplate.all
  end

  # GET /mail_templates/1
  # GET /mail_templates/1.json
  def show
  end

  # GET /mail_templates/new
  def new
    @mail_template = MailTemplate.new
  end

  # GET /mail_templates/1/edit
  def edit
  end

  def send_mail_template
    if @mail_template.update(mail_template_params)      
      if @mail_template.mail_list.present?
        mail_list_param = @mail_template.mail_list.split(",").present? ? @mail_template.mail_list.split(",") : [@mail_template.mail_list]
        begin
          TemplateMailer.template_sender(mail_list_param, 
              @mail_template.subject,
              @mail_template.content)
        rescue Exception
          respond_to do |format|
            format.json { render json: {:mail_list => "There was an error on delivery mail task, please check the file format and try again"}, status: 404 }
          end  
        end
      else
        respond_to do |format|
          format.json { render json: {:mail_list => "Must not be empty"}, status: 404 }
        end
      end
    else
      respond_to do |format|
        format.json { render json: @mail_template.errors.messages, status: :unprocessable_entity }
      end
    end
    # redirect code here
  end

  def send_csv_mail_template
    if @mail_template.update(mail_template_params)      
      if @mail_template.csv.present? && (@mail_template.csv.content_type == "text/csv" || @mail_template.csv.content_type == "application/vnd.ms-excel")
        begin
          mail_array = @mail_template.readFile
          if mail_array.present?
            TemplateMailer.template_sender(mail_array, 
              @mail_template.subject,
              @mail_template.content)
          else 
            respond_to do |format|
              format.json { render json: {:csv => "The file is empty"}, status: 404 }
            end
          end
        rescue Exception
          respond_to do |format|
            format.json { render json: {:"" => "Please check the file format and try again"}, status: 404 }
          end  
        end
      else
        respond_to do |format|
          format.json { render json: {:csv => "is not a CSV file"}, status: 404 }
        end
      end
    else
      respond_to do |format|
        format.json { render json: @mail_template.errors.messages, status: :unprocessable_entity }
      end
    end
    # redirect code here
  end

  # POST /mail_templates
  # POST /mail_templates.json
  def create
    @mail_template = MailTemplate.new(mail_template_params)

    respond_to do |format|
      if @mail_template.save
        format.html { redirect_to @mail_template, notice: 'Mail template was successfully created.' }
        format.json { render :show, status: :created, location: @mail_template }
      else
        format.html { render :new }
        format.json { render json: @mail_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mail_templates/1
  # PATCH/PUT /mail_templates/1.json
  def update
    respond_to do |format|
      if @mail_template.update(mail_template_params)
        format.html { redirect_to @mail_template, notice: 'Mail template was successfully updated.' }
        format.json { render :show, status: :ok, location: @mail_template }
      else
        format.html { render :edit }
        format.json { render json: @mail_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mail_templates/1
  # DELETE /mail_templates/1.json
  def destroy
    @mail_template.destroy
    respond_to do |format|
      format.html { redirect_to mail_templates_url, notice: 'Mail template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy
    @mail_template.destroy
    respond_to do |format|
      format.html { redirect_to mail_templates_url, notice: 'Age Range was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def destroy_multiple
    params[:mail_template_ids].each do |id|
      @mail_template = MailTemplate.find(id)
      @mail_template.destroy
    end
    respond_to do |format|
      format.html { redirect_to mail_templates_path, notice: 'Registros eliminados exitosamente.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mail_template
      @mail_template = MailTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mail_template_params
      params.require(:mail_template).permit(:mail_list, :subject, :content, :bootsy_image_gallery_id, :csv)
    end
end

app/helpers/mail_templates_helper.rb
module MailTemplatesHelper
end

app/views/mail_templates/_form.html.erb
<%= form_for(mail_template, html: {:class=>"form-horizontal form-label-left template_form", :novalidate => nil, multipart: true}) do |f| %>
  <% if mail_template.errors.any? %>
    <div id="error_explanation" class="alert-danger">
      <h2><%= pluralize(mail_template.errors.count, "error") %> prohibited this mail_template from being saved:</h2>

      <ul>
        <% mail_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if !f.object.new_record?%>

    <div class="item form-group">
      <%= f.label :csv, :class=>"control-label col-md-12 col-sm-12 col-xs-12" do %>
      Mail List CSV (just for send mail, this info is not going to be stored)
      <%end%> 
      <div class="col-md-12 col-sm-12 col-xs-12">
        <%= f.file_field :csv, :class=>"form-control col-md-7 col-xs-12", :accept=>".csv" %>
      </div>
    </div>
    <p class="button upload"></p>
    <hr>
    <br>

    <div class="item form-group">
      <%= f.label :mail_list, :class=>"control-label col-md-12 col-sm-12 col-xs-12" do %>
      Mail List (just for send mail, this info is not going to be stored)
      <%end%> 
      <div class="col-md-12 col-sm-12 col-xs-12">
        <%= f.text_field :mail_list, :class=>"form-control col-md-7 col-xs-12" %>
      </div>
    </div>
    <%=link_to("Cancelar", mail_templates_path, :class=>"btn btn-primary")%>
    <button id="send" type="submit" class="btn btn-success">Save</button>
    <%= content_tag(:a, "Update and Send Mail", :class => "btn btn-success send_mail")%>
    <hr>
    <br>
  <%end%>

  <div class="item form-group">
    <%= f.label :subject, :class=>"control-label col-md-1 col-sm-1 col-xs-12" do %>
    subject <span class="required">*
    <%end%> 
    <div class="col-md-11 col-sm-11 col-xs-12">
      <%= f.text_field :subject, :class=>"form-control col-md-7 col-xs-12",:required=>"required" %>
    </div>
  </div>

  <div class="item form-group">
    <%= f.label :content, :class=>"control-label col-md-1 col-sm-1 col-xs-12" do %>
    Template <span class="required">*
    <%end%> 
    <div class="col-md-11 col-sm-11 col-xs-12">
      <%= f.bootsy_area :content, :class=>"form-control col-md-7 col-xs-12", editor_options: { :blockquote => true, :font_styles => true, :emphasis => true, :lists => true, :html => true, :link => true, :image => true, :color => true, table: true, tr: true, td: true }%>
    </div>
  </div>
  <% if f.object.new_record?%>
    <div class="form-group">
      <div class="col-md-6 col-md-offset-3">
        <%=link_to("Cancelar", mail_templates_path, :class=>"btn btn-primary")%>
        <button id="send" type="submit" class="btn btn-success">Save</button>
      </div>
    </div>
  <%end%>
  <% if !f.object.new_record?%>
    <script>

      $(document).ready(function(){
        $(".send_mail").on("click",function(){
          var template_form = $(".template_form").serialize();
          $.getScript("<%= send_mail_template_path %>?"+template_form, function() { })
          .done(function( s, Status ) {
            alert("The mail has been delivered successfully");
          })
          .fail(function( jqxhr, settings, exception ) {
            
            var exceptionMessages = ""
            if (IsJsonString(jqxhr.responseText)){
              var array = JSON.parse(jqxhr.responseText);
              jQuery.each(array, function(i, val) {
                exceptionMessages += i + " " + val + "\n";
              });
            }else {
              exceptionMessages += jqxhr.responseText;
            }
            
            alert("Please try Again, the mail could not be delivered\n" + exceptionMessages);
          });;
        });  
        
        $('input[type="file"]').fileupload({
          url: "<%= send_csv_mail_template_path %>",
          type: "PATCH",
          dataType: 'json',
          add: function (e, data) {
              $(".button.upload").html("");
              data.context = $('<button/>').html('Update and Send Mail To CSV file').addClass("btn btn-success send_csv_mail")
                .appendTo($(".button.upload"))
                .click(function () {
                    data.context = $('<p/>').text('Uploading...').replaceAll($(this));
                    data.submit();
                });
          },
          done: function (e, data) {
              $(".button.upload").html("");
              data.context.text('Upload finished.');
              $.each(data.result.files, function (index, file) {
                  alert("The mail has been delivered successfully");
              });
          },
          fail: function( e, data ) {
            var exceptionMessages = ""
            jqxhr = data._response.jqXHR;
            if (IsJsonString(jqxhr.responseText)){
              var array = JSON.parse(jqxhr.responseText);
              jQuery.each(array, function(i, val) {
                exceptionMessages += i + " " + val + "\n";
              });
            }else {
              exceptionMessages += jqxhr.responseText;
            }
            $(".button.upload").html("");
            data.context.text('File could not be uploaded');
            alert("Please try Again, the mail could not be delivered\n" + exceptionMessages);
          },
          progressall: function (e, data) {
            var progress = parseInt(data.loaded / data.total * 100, 10);
            $('#progress .bar').css(
                'width',
                progress + '%'
            );
          }
        });




        function IsJsonString(str) {
          try {
              JSON.parse(str);
          } catch (e) {
              return false;
          }
          return true;
        }
      });
    </script>
  <%end%>
<% end %>

app/views/mail_templates/edit.html.erb
<div class="right_col" role="main">
	<div class="">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>Edit Template (<%=@mail_template.subject%>)</h2>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<%= render 'form', mail_template: @mail_template %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/mail_templates/index.html.erb
<div class="right_col" role="main">
  <div class="">

    <div class="clearfix"></div>

    <div class="row">

      <div class="clearfix"></div>

      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Mail Templates</h2>
            <ul class="nav navbar-right panel_toolbox panel_button">
              <li>
                <%= link_to(content_tag(:i, nil, :class=>"fa  fa-plus"),new_mail_template_path, :"data-toggle"=>"tooltip", :"data-placement"=>"top", :title=>"", :rel=>"nofollow", :"data-original-title"=>"New")%>
              </li>
            </ul>
            <div class="clearfix"></div>
          </div>

          <div class="x_content">
            <% if notice.present?%>
              <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                <%= notice %>
              </div>
            <% end %>
            <div class="table-responsive">
              <%= form_tag destroy_multiple_mail_templates_path, method: :delete, data: { confirm: "Are you sure?"}, :class=>"multi_delete_form" do %>
                <table class="table table-striped jambo_table bulk_action">
                  <thead>
                    <tr class="headings">
                      <th>
                        <input type="checkbox" id="check-all" class="flat">
                      </th>
                      <th class="column-title">Subject</th>
                      <th class="column-title no-link last" colspan="3">Action</th>
                      </th>
                      <th class="bulk-actions" colspan="7">
                        <a type="button" id="delete_records" class="antoo submit-form" style="color:#fff; font-weight:500; cursor:pointer">Eliminar ( <span class="action-cnt"> </span> ) <i class="fa fa-trash-o"></i></button>
                      </th>
                    </tr>
                  </thead>

                  <tbody>
                    <% @mail_templates.each_with_index do |mail_template, index| %>
                      <tr class="<%= index.odd? ? 'odd' : 'even'%> pointer">
                        <td class="center">
                                    <input type="checkbox" name="mail_template_ids[]" id="mail_template_id_<%=mail_template.id%>" value="<%=mail_template.id%>" class="flat deletable">
                              </td>

                        <td><%= mail_template.subject %></td>

                        <td class=" last"><%= link_to content_tag(:i,nil,:class=>"fa fa-search"), mail_template %></td>
                        <td class=" last"><%= link_to content_tag(:i,nil,:class=>"fa fa-paper-plane"), edit_mail_template_path(mail_template) %></td>
                        <td class=" last"><%= link_to content_tag(:i,nil,:class=>"fa fa-trash-o"), mail_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                    <% end %>
                  </tbody>

                </table>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/mail_templates/new.html.erb
<div class="right_col" role="main">
	<div class="">
		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<div class="x_title">
						<h2>New Template</h2>
						<div class="clearfix"></div>
					</div>
					<div class="x_content">
						<%= render 'form', mail_template: @mail_template %>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/mail_templates/show.html.erb
<div class="right_col" role="main" style="min-height: 1053px;">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3><%=@mail_template.subject %></h3>
      </div>
    </div>

    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12">

        <div class="x_panel">

          <div class="x_content">
            <% if notice.present?%>
              <div class="alert alert-success">
                <a href="#" class="close" data-dismiss="alert" aria-label="close" title="close">×</a>
                <%= notice %>
              </div>
            <% end %>
            <div class="col-md-8 col-lg-8 col-sm-7">
              <!-- blockquote -->
              <blockquote>

                <h2>Subject:</h2>
                <h4><%= @mail_template.subject %></h4>
                
                <h2>Template:</h2>
                <h4><%= @mail_template.content.html_safe %></h4>
                
              </blockquote>

              <blockquote class="blockquote-reverse">

                  <%= link_to 'Editar', edit_mail_template_path(@mail_template), :class=>"btn btn-primary" %>
                  <%= link_to 'Atrás', mail_templates_path, :class=>"btn btn-success" %>

              </blockquote>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>