config/routes.rb
Rails.application.routes.draw do
	mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	devise_for :users, class_name: "User",
	:controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions', :passwords => 'users/passwords' },
	path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
	root :to => "dashboard#index"
	resources :mail_templates do
		collection do
			delete 'destroy_multiple'
		end
	end
	get "send_mail_template/:id", to: 'mail_templates#send_mail_template', as: :send_mail_template
	patch "send_csv_mail_template/:id", to: 'mail_templates#send_csv_mail_template', as: :send_csv_mail_template
end

app/views/shared/_footer.html.erb
<footer>
	<div class="pull-right">
		CIE powered by <a href="#">BI</a>
	</div>
	<div class="clearfix"></div>
</footer>

app/views/shared/_registration_form.html.erb
<!-- page content -->
<div class="right_col" role="main">
	<div class="">
		<div class="page-title">
			<div class="title_left">
				<h3>User Profile</h3>
			</div>

		</div>
		
		<div class="clearfix"></div>

		<div class="row">
			<div class="col-md-12 col-sm-12 col-xs-12">
				<div class="x_panel">
					<%= devise_error_messages! %>
					<div class="x_content">

						<div class="col-md-3 col-sm-3 col-xs-12 profile_left">

							<div class="profile_img">

								<!-- end of image cropping -->
								<div id="crop-avatar">
									<!-- Current avatar -->
									<%=image_tag(resource.image_source("avatar"), :style=>"max-width: 200px", :class=>"img-responsive avatar-view",	 :alt=>"#{resource.name}", :title=>"#{resource.name}")%>

									<!-- Cropping modal -->
									<div class="modal fade" id="avatar-modal" aria-hidden="true" aria-labelledby="avatar-modal-label" role="dialog" tabindex="-1">
										<div class="modal-dialog modal-lg">
											<div class="modal-content">

											</div>
										</div>
									</div>
									<!-- /.modal -->

									<!-- Loading state -->
									<div class="loading" aria-label="Loading" role="img" tabindex="-1"></div>
								</div>
								<!-- end of image cropping -->

							</div>
							<h3><%=resource.name%></h3>

							<ul class="list-unstyled user_data">
								<li><i class="fa fa-map-marker user-profile-icon"></i> CIE
								</li>

								<li>
									<i class="fa fa-briefcase user-profile-icon"></i> Role
								</li>

							</ul>

						</div>
						<div class="col-md-9 col-sm-9 col-xs-12">
							<div class="clearfix"></div>
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="x_panel">

										<div class="x_content">
											<br />
											<%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put, :"data-parsley-validate" => nil, :class=>"form-horizontal form-label-left" }) do |f| %>

											<div class="form-group">
												<%=f.label :name, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do%>
													User Name <span class="required">*</span>
												<%end%>
												<div class="col-md-6 col-sm-6 col-xs-12">
													<%= f.text_field :name, autofocus: true, :class=>"form-control col-md-7 col-xs-12", :placeholder => "User Name", :required=>"required" %>
												</div>
											</div>
											<div class="form-group">
												<%=f.label :email, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do%>
													eMail <span class="required">*</span>
												<%end%>
												<div class="col-md-6 col-sm-6 col-xs-12">
													<%= f.email_field :email, :placeholder => "eMail", :class=>"form-control col-md-7 col-xs-12", :required=>"required" %>
												</div>
											</div>
											<div class="form-group">
												<%=f.label :avatar, :class=>"control-label col-md-3 col-sm-3 col-xs-12"%>
												<div class="col-md-6 col-sm-6 col-xs-12">
													<%= f.file_field :avatar, :placeholder => "Avatar" %>
												</div>
											</div>
											<div class="form-group">
												<%=f.label :password, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do%>
													New Password <i>(Leave in blank if you don´t want to update it)</i>
												<%end%>
												<div class="col-md-6 col-sm-6 col-xs-12">
													<%= f.password_field :password, autocomplete: "off", :class=>"form-control col-md-7 col-xs-12"  %>
													<% if @minimum_password_length %>
													<br />
													<em>At least <%= @minimum_password_length %> characters</em>
													<% end %>
												</div>
											</div>
											<div class="form-group">
												<%=f.label :password_confirmation, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do%>
													Password Confirmation
												<%end%>
												<div class="col-md-6 col-sm-6 col-xs-12">
													<%= f.password_field :password_confirmation, autocomplete: "off", :class=>"form-control col-md-7 col-xs-12"  %>
												</div>
											</div>
											<div class="ln_solid"></div>
											<h4>Necesitamos tu contraseña actual para validar y realizar los cambios</h4>
											<div class="form-group">
												<%=f.label :password, :class=>"control-label col-md-3 col-sm-3 col-xs-12" do%>
													Current Password
												<%end%>
												<div class="col-md-6 col-sm-6 col-xs-12">
													<%= f.password_field :current_password, autocomplete: "off", :class=>"form-control col-md-7 col-xs-12"  %>
												</div>
											</div>

											<div class="ln_solid"></div>
											<div class="form-group">
												<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
													<%= link_to "Cancel", session_root_path, :class=>"btn btn-primary"%>
													<%= f.submit "Update", :class=>"btn btn-success"%>
												</div>
											</div>

											<% end %>
										</div>
									</div>
								</div>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>