config/routes.rb
Rails.application.routes.draw do
	mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	devise_for :users, class_name: "User",
	:controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions', :passwords => 'users/passwords' },
	path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }
	root :to => "dashboard#index"
	resources :mail_templates do
		collection do
			delete 'destroy_multiple'
		end
	end
	get "send_mail_template/:id", to: 'mail_templates#send_mail_template', as: :send_mail_template
	patch "send_csv_mail_template/:id", to: 'mail_templates#send_csv_mail_template', as: :send_csv_mail_template
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%=@page_title%></title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<!-- jVectorMap -->
	<script src="/assets/maps/jquery-jvectormap-world-mill-en.js"></script>
	<script src="/assets/maps/jquery-jvectormap-us-aea-en.js"></script>
	<script src="/assets/maps/gdp-data.js"></script>
	<%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
	<%= favicon_link_tag 'favicon.ico'%>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes"/>
</head>

<body class="nav-md footer_fixed">
	<div class="container body">
		<div class="main_container">
			<div class="col-md-3 left_col menu_fixed">
				<div class="left_col scroll-view">
					<div class="navbar nav_title" style="border: 0;">
						<a href="<%=session_root_path%>" class="site_title"><i class="fa fa-cogs"></i> <span>MailThem</span></a>
					</div>

					<div class="clearfix"></div>

					<!-- menu profile quick info -->
					<div class="profile clearfix">
						<div class="profile_pic">
							<%=image_tag(current_user.image_source("avatar"), :class=>"img-circle profile_img",  :alt=>"#{current_user.name.to_s}", :title=>"#{current_user.name.to_s}")%>
						</div>
						<div class="profile_info">
							<span>Welcome,</span>
							<h2><%=current_user.name.to_s%></h2>
						</div>
					</div>
					<!-- /menu profile quick info -->

					<br />
					<!-- sidebar menu -->
					<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
						<div class="menu_section">
							<h3>General</h3>
							<ul class="nav side-menu">
								<li class="<%= current_page(DashboardController)%>"><a href="<%=session_root_path%>"><i class="fa fa-home"></i> Dashboard</a>
								</li>
								<li><a><i class="fa fa-child"></i>Template Builder <span class="fa fa-chevron-down"></span></a>
									<ul class="nav child_menu">
										<li class="<%= current_page(MailTemplatesController)%>"><%=link_to "Templates",mail_templates_path%></li>
									</ul>
								</li>
							</ul>
						</div>

					</div>
					<!-- /sidebar menu -->
					<script>
						$(".current-page").parent().parent().addClass("active");
						$(".current-page").parent().css("display","block");
					</script>
					<!-- /menu footer buttons -->
					<%=footer_menu%>
					<!-- /menu footer buttons -->
				</div>
			</div>

			<!-- top navigation -->
			<%=top_nav_menu%>
			<!-- /top navigation -->

			<!-- page content -->
			<%=yield%>
			<!-- /page content -->

			<!-- footer content -->
			<footer>
				<div class="pull-right">
					MailThem powered by <a href="#">DotCreek</a>
				</div>
				<div class="clearfix"></div>
			</footer>
			<!-- /footer content -->
		</div>
	</div>
</body>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%=@page_title%></title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'false' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'false' %>
	<%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
	<%= favicon_link_tag 'favicon.ico'%>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes"/>
</head>
<body class="login">
	<%=devise_error_messages!%>
	<div>
		<div class="login_wrapper">
			<div class="animate form login_form">
				<section class="login_content">
					<%= yield%>
				</section>
			</div>
		</div>
	</div>
</body>
</html>